### ISSUE TITLE
Sigmund~ has gone 404

### ISSUE THREAD

**Issue by z-plane** [stretta/BEAP#16]
I wasnt sure where / who to notify about this as I'm just checking BEAP out, so apologies if this isnt the right place. Basically the URL in the installation process for sigmund~ is dead, I believe the website was just redesigned which may explain the broken link.

Nice work so far BTW!

**Comment by stretta** [comment]
the 64 bit calibration uses fzero, but the original sigmund~ version is still available if you want to install sigmund~, or if sigmund~ ever gets recompiled for 64-bit.
