### ISSUE TITLE
Waveform dropdown in bp.Macro Oscillator not Parameter Mode enabled

### ISSUE THREAD

**Issue by robmaxtech** [stretta/BEAP#47]
Hi,

first I have to say that BEAP is simply great! Gives the feeling real modular synth with the advantages of the MAX world - wonderful!
Playing around with the modules I found that in bp.Macro Oscillator the Parameter Mode is not enabled for the umenu with the generators and therefore the setting is not saved e.g. in a pattrstorage; or have i overlooked something? btw, I'm using BEAP in the M4L environment.

Cheers 
Rob

**Comment by tildebyte** [comment]
I, too, had issues with the Macro and presets, but I wasn't able to track them down.
