### ISSUE TITLE
Q: git-BEAP and Max7-BEAP coexistence

### ISSUE THREAD

**Issue by tildebyte** [stretta/BEAP#50]
Any advice? Overwrite Max7-BEAP with git-BEAP master? Add git-BEAP to Max 7 as a separate package? Something I haven't thought of?
I ask because I'm the typical early-adopter, and I like to mess around with stuff in the dev branch, even.

**Comment by baptistemanson** [comment]
Hi Tildebyte,

I tried to update the documentation to explain the procedure I used.
https://github.com/stretta/BEAP/wiki/BEAP-Modular---Overview-and-Install
In the section Install from source, and use section in particular.

I am by no mean an expert, but it did work great for me so far.
PS: And if you like to mess around, you can do your own fork to save your work!

**Comment by tildebyte** [comment]
Seems to work OK.
The only thing which concerns me: modules from the git folder (in e.g. `My Documents/Max 7/packages/BEAP`) appear in the BEAP "palette" (lowercase '*b*' on the left side of the patcher window). I know this because the git-only `bp.Poisson Pulse` is there.
Which version of modules appearing in both places shows up in the palette?

**Comment by megamaeng** [comment]
Is there any way to have the latest git folder replace the built in beap modules in max 7? Right now, following the max 7 install directions in the wiki, there are 2 copies of the same object when using the lowercase 'b' in the patcher window and I'd prefer not to have to use the right click contextual menu.

Thanks!
