### ISSUE TITLE
freq shifter does not pass effected audio

### ISSUE THREAD

**Issue by stretta** [stretta/BEAP#51]
The frequency shifter module seems busted. Dry audio can pass, but not effected audio. poly abstraction seems found, so I'm not sure what the issue is.

**Comment by petermcculloch** [comment]
This was fixed on April 3rd.  (It may not have made it into the newest official release?)  

The old version was missing the correct connections to the poly~.  It looks like the poly~ object is not connected when I instantiate it from the toolbar, but I don't think I've upgraded from that version yet.  

When I copy and paste the raw text for bp.Frequency Shifter from GitHub, it runs correctly.  Can you confirm?

**Comment by stretta** [comment]
Sorry. repo / working directory issue on my end. Closing.
