### ISSUE TITLE
Gate Seq GUI issue when saving withing Max 4 Live device.

### ISSUE THREAD

**Issue by dphelmer** [stretta/BEAP#53]
The gate selection portion of the module turns into more of a note sequencer when saving within a max 4 live device.

![gate](https://cloud.githubusercontent.com/assets/6432433/11108590/045b796a-88b6-11e5-9efb-0d310c3fcf18.jpg)

**Comment by unriginal** [comment]
Is this in Max 6 or 7? Also, does this happen when you save, or after you've re-opened the patch (for me, it's the latter)?

**Comment by dphelmer** [comment]
Max 7.0.6, Live 9.5, and I just did a fresh pull from git.
Before I thought it happened when saving, but when I just re-did the process it seems to happen when pulling a new instance of the saved patch from Live's left hand pane.

**Comment by dphelmer** [comment]
Yup fixed, thanks!
