### ISSUE TITLE
Question: CV trigger train

### ISSUE THREAD

**Issue by DepreTux** [stretta/BEAP#59]
Hi!

I have a question related to beap, and I don't know where to ask. I hope this is the right place, since I haven't found any forums or such.
My question is the following; how do I issue a limited amount of triggers. I'd like to have my midi controller fire a sequence from its beggining up to say the eight step each time I press a key.
I do have some basic knowledge on puredata so I could make this on my own, but I ignore the way beap handles CV gate and trigger.

Please direct me to the right place to ask if this is not

Thanks for making beap available to everyone. In my opinion this is the best modular soft synth available. I particularly appreciate the diode ladder filter.

Have a good one!

**Comment by stretta** [comment]
I'm not sure if I understand you correctly, but you can drive the sequencer module to advance to the next stage with a trigger.

<pre><code>
----------begin_max5_patcher----------
515.3oc6U0yaaCCDcV5Wg.mcMzGNRNctCwCcJiEEETTWjXhLoCIkqMBx+8xu
rKsiZrqQ8RPWDEu6HuGu26HeINBUy2.RTxmS9VRTzKwQQVSFCQ94Qnk3Mjdr
zFFpdEVQ5.AZhy4ZrfgWBdeSuiJUbw18dovOWSkzZZOUs0DTl2C+gGjfxk4z
ooSLeR9t2YOm7DzzHvsRhf22aBK06izSIOo5D7g1tP6.CW2CcucANGqeqi51
k7F3.KbQi9nEXgMrjx5AkLD6vFk.STglrUEJq8GBf3OUEyJLmqxr4lgr7L6P
VYv4Tu67A0wa+H0yoZNPmhckU2hTaWAtTgjzVFVe31swzF6Fvqe7SkoHisWi
iMel7ugluGdd.Xj.+enH57KgnKlcqYnJuzLjWj+GI57QH58Uzyjpm7tj9M2d
EH8ut3KKRT7j68H3+s34U1l57LKkmUVbpV7aFg4Orr9WS+u+eiJNlesDGKXe
LUEoWhpnxcueQwkbuuubdJ0.koFmhqBoXaDndJ63m5sf2X+PdWxGDjcovech
lm1mnFPpnLrhxYAAoenILnNZSCvBqdMTogPrnLcTE3Yim45TkeB7bDnup3o5
LpOVPeI3wQe3UqVCBoeOsPQ2f9H2pZqlXmRYtoVEER.lNP9uyABKzZUkVnNH
bJsMkyPtkpaHDrApc0wlL+Z7u3QqyYN
-----------end_max5_patcher-----------
</code></pre>

**Comment by DepreTux** [comment]
Thanks for the answer.

My question is, for example, how could I make the sequencer take only 8 steps and then stop (if possible following ableton's transport tempo).

I was thinking of using the trigger input in the sequencer, but I need to figure a patch that will output those 8 trigger signals, for instance, every 16th note.
The problem is I don't know how to translate from Max's bangs to beap's triggers.

I'm probably not being crystal clear, but english is not my native language, sorry.

**Comment by petermcculloch** [comment]
You can convert a bang into a trigger signal by sending it into this:
click~ 5.



On Tue, Feb 9, 2016 at 2:07 PM, DepreTux <notifications@github.com> wrote:

> Thanks for the answer.
>
> My question is, for example, how could I make the sequencer take only 8
> steps and then stop (if possible following ableton's transport tempo).
>
> I was thinking of using the trigger input in the sequencer, but I need to
> figure a patch that will output those 8 trigger signals, for instance,
> every 16th note.
> The problem is I don't know how to translate from Max's bangs to beap's
> triggers.
>
> I'm probably not being crystal clear, but english is not my native
> language, sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stretta/BEAP/issues/59#issuecomment-182009559>.
>



-- 
www.petermcculloch.com

**Comment by DepreTux** [comment]
Thanks, I didn't know it was so easy!
