### ISSUE TITLE
Sequencer pattern setting - morphing vs. fixed

### ISSUE THREAD

**Issue by darwingrosse** [stretta/BEAP#60]
I noticed with the 'fixed' Sequencer, the pattern selection acts like a morphing control (morphing between pattr settings, I guess) rather than in 12 discrete steps. Since there is no way to programmatically set the pattern, and there isn't much clarity about when you are actually at the right position, I would like to change this to use 12 steps instead of interim values.

Also, note that the morphing drives live.grid a little crazy with inappropriate morphed values.

I'm going to make the change locally, and will update unless I hear from someone that this is undesirable.

[ddg]

**Comment by stretta** [comment]
OK to merge this in.

**Comment by darwingrosse** [comment]
Done - thanks!
